//
//  FlagEnum.swift
//  WorldFlags
//
//  Created by Robert Bradish on 28/06/2020.
//

import Foundation

public enum CountryFlag: String, CaseIterable, Codable {
    case RNB = "🏳️‍🌈"
    case AFG = "🇦🇫"
    case ALB = "🇦🇱"
    case DZA = "🇩🇿"
    case ASM = "🇦🇸"
    case AND = "🇦🇩"
    case AGO = "🇦🇴"
    case AIA = "🇦🇮"
    case ATA = "🇦🇶"
    case ATG = "🇦🇬"
    case ARG = "🇦🇷"
    case ARM = "🇦🇲"
    case ABW = "🇦🇼"
    case AUS = "🇦🇺"
    case AUT = "🇦🇹"
    case AZE = "🇦🇿"
    case BHS = "🇧🇸"
    case BHR = "🇧🇭"
    case BGD = "🇧🇩"
    case BRB = "🇧🇧"
    case BLR = "🇧🇾"
    case BEL = "🇧🇪"
    case BLZ = "🇧🇿"
    case BEN = "🇧🇯"
    case BMU = "🇧🇲"
    case BTN = "🇧🇹"
    case BOL = "🇧🇴"
    case BES = "🇧🇦"
    case BWA = "🇧🇼"
    case BRA = "🇧🇷"
    case IOT = "🇮🇴"
    case BRN = "🇧🇳"
    case BGR = "🇧🇬"
    case BFA = "🇧🇫"
    case BDI = "🇧🇮"
    case CPV = "🇨🇻"
    case KHM = "🇰🇭"
    case CMR = "🇨🇲"
    case CAN = "🇨🇦"
    case CYM = "🇰🇾"
    case CAF = "🇨🇫"
    case TCD = "🇹🇩"
    case CHL = "🇨🇱"
    case CHN = "🇨🇳"
    case CXR = "🇨🇽"
    case CCK = "🇨🇨"
    case COL = "🇨🇴"
    case COM = "🇰🇲"
    case COD = "🇨🇩"
    case COG = "🇨🇬"
    case COK = "🇨🇰"
    case CRI = "🇨🇷"
    case HRV = "🇭🇷"
    case CUB = "🇨🇺"
    case CUW = "🇨🇼"
    case CYP = "🇨🇾"
    case CZE = "🇨🇿"
    case CIV = "🇨🇮"
    case DNK = "🇩🇰"
    case DJI = "🇩🇯"
    case DMA = "🇩🇲"
    case DOM = "🇩🇴"
    case ECU = "🇪🇨"
    case EGY = "🇪🇬"
    case SLV = "🇸🇻"
    case GNQ = "🇬🇶"
    case ERI = "🇪🇷"
    case EST = "🇪🇪"
    case SWZ = "🇸🇿"
    case ETH = "🇪🇹"
    case FLK = "🇫🇰"
    case FRO = "🇫🇴"
    case FJI = "🇫🇯"
    case FIN = "🇫🇮"
    case FRA = "🇫🇷"
    case GUF = "🇬🇫"
    case PYF = "🇵🇫"
    case ATF = "🇹🇫"
    case GAB = "🇬🇦"
    case GMB = "🇬🇲"
    case GEO = "🇬🇪"
    case DEU = "🇩🇪"
    case GHA = "🇬🇭"
    case GIB = "🇬🇮"
    case GRC = "🇬🇷"
    case GRL = "🇬🇱"
    case GRD = "🇬🇩"
    case GLP = "🇬🇵"
    case GUM = "🇬🇺"
    case GTM = "🇬🇹"
    case GGY = "🇬🇬"
    case GIN = "🇬🇳"
    case GNB = "🇬🇼"
    case GUY = "🇬🇾"
    case HTI = "🇭🇹"
    case VAT = "🇻🇦"
    case HND = "🇭🇳"
    case HKG = "🇭🇰"
    case HUN = "🇭🇺"
    case ISL = "🇮🇸"
    case IND = "🇮🇳"
    case IDN = "🇮🇩"
    case IRN = "🇮🇷"
    case IRQ = "🇮🇶"
    case IRL = "🇮🇪"
    case IMN = "🇮🇲"
    case ISR = "🇮🇱"
    case ITA = "🇮🇹"
    case JAM = "🇯🇲"
    case JPN = "🇯🇵"
    case JEY = "🇯🇪"
    case JOR = "🇯🇴"
    case KAZ = "🇰🇿"
    case KEN = "🇰🇪"
    case KIR = "🇰🇮"
    case PRK = "🇰🇵"
    case KOR = "🇰🇷"
    case KWT = "🇰🇼"
    case KGZ = "🇰🇬"
    case LAO = "🇱🇦"
    case LVA = "🇱🇻"
    case LBN = "🇱🇧"
    case LSO = "🇱🇸"
    case LBR = "🇱🇷"
    case LBY = "🇱🇾"
    case LIE = "🇱🇮"
    case LTU = "🇱🇹"
    case LUX = "🇱🇺"
    case MAC = "🇲🇴"
    case MDG = "🇲🇬"
    case MWI = "🇲🇼"
    case MYS = "🇲🇾"
    case MDV = "🇲🇻"
    case MLI = "🇲🇱"
    case MLT = "🇲🇹"
    case MHL = "🇲🇭"
    case MTQ = "🇲🇶"
    case MRT = "🇲🇷"
    case MUS = "🇲🇺"
    case MYT = "🇾🇹"
    case MEX = "🇲🇽"
    case FSM = "🇫🇲"
    case MDA = "🇲🇩"
    case MCO = "🇲🇨"
    case MNG = "🇲🇳"
    case MNE = "🇲🇪"
    case MSR = "🇲🇸"
    case MAR = "🇲🇦"
    case MOZ = "🇲🇿"
    case MMR = "🇲🇲"
    case NAM = "🇳🇦"
    case NRU = "🇳🇷"
    case NPL = "🇳🇵"
    case NLD = "🇳🇱"
    case NCL = "🇳🇨"
    case NZL = "🇳🇿"
    case NIC = "🇳🇮"
    case NER = "🇳🇪"
    case NGA = "🇳🇬"
    case NIU = "🇳🇺"
    case NFK = "🇳🇫"
    case MNP = "🇲🇵"
    case NOR = "🇳🇴"
    case OMN = "🇴🇲"
    case PAK = "🇵🇰"
    case PLW = "🇵🇼"
    case PSE = "🇵🇸"
    case PAN = "🇵🇦"
    case PNG = "🇵🇬"
    case PRY = "🇵🇾"
    case PER = "🇵🇪"
    case PHL = "🇵🇭"
    case PCN = "🇵🇳"
    case POL = "🇵🇱"
    case PRT = "🇵🇹"
    case PRI = "🇵🇷"
    case QAT = "🇶🇦"
    case MKD = "🇲🇰"
    case ROU = "🇷🇴"
    case RUS = "🇷🇺"
    case RWA = "🇷🇼"
    case REU = "🇷🇪"
    case BLM = "🇧🇱"
    case SHN = "🇬🇸"
    case KNA = "🇰🇳"
    case LCA = "🇱🇨"
    case SPM = "🇵🇲"
    case VCT = "🇻🇨"
    case WSM = "🇼🇸"
    case SMR = "🇸🇲"
    case SAU = "🇸🇦"
    case SEN = "🇸🇳"
    case SRB = "🇷🇸"
    case SYC = "🇸🇨"
    case SLE = "🇸🇱"
    case SGP = "🇸🇬"
    case SXM = "🇸🇽"
    case SVK = "🇸🇰"
    case SVN = "🇸🇮"
    case SLB = "🇸🇧"
    case SOM = "🇸🇴"
    case ZAF = "🇿🇦"
    case SGS = "🇸🇭"
    case SSD = "🇸🇸"
    case ESP = "🇪🇸"
    case LKA = "🇱🇰"
    case SDN = "🇸🇩"
    case SUR = "🇸🇷"
    case SWE = "🇸🇪"
    case CHE = "🇨🇭"
    case SYR = "🇸🇾"
    case TWN = "🇹🇼"
    case TJK = "🇹🇯"
    case TZA = "🇹🇿"
    case THA = "🇹🇭"
    case TLS = "🇹🇱"
    case TGO = "🇹🇬"
    case TKL = "🇹🇰"
    case TON = "🇹🇴"
    case TTO = "🇹🇹"
    case TUN = "🇹🇳"
    case TUR = "🇹🇷"
    case TKM = "🇹🇲"
    case TCA = "🇹🇨"
    case TUV = "🇹🇻"
    case UGA = "🇺🇬"
    case UKR = "🇺🇦"
    case ARE = "🇦🇪"
    case GBR = "🇬🇧"
    case USA = "🇺🇸"
    case URY = "🇺🇾"
    case UZB = "🇺🇿"
    case VUT = "🇻🇺"
    case VEN = "🇻🇪"
    case VNM = "🇻🇳"
    case VGB = "🇻🇬"
    case VIR = "🇻🇮"
    case WLF = "🇼🇫"
    case ESH = "🇪🇭"
    case YEM = "🇾🇪"
    case ZMB = "🇿🇲"
    case ZWE = "🇿🇼"
    case ALA = "🇦🇽"
    
    public init?(iso3: String) {
        switch iso3 {
        case "RNB": self.init(rawValue: "🏳️‍🌈")
        case "AFG": self.init(rawValue: "🇦🇫") // "Afghanistan"
        case "ALB": self.init(rawValue:"🇦🇱") // "Albania"
        case "DZA": self.init(rawValue:"🇩🇿") // "Algeria"
        case "ASM": self.init(rawValue:"🇦🇸") // "American Samoa"
        case "AND": self.init(rawValue:"🇦🇩") // "Andorra"
        case "AGO": self.init(rawValue:"🇦🇴") // "Angola"
        case "AIA": self.init(rawValue:"🇦🇮") // "Anguilla"
        case "ATA": self.init(rawValue:"🇦🇶") // "Antarctica"
        case "ATG": self.init(rawValue:"🇦🇬") // "Antigua and Barbuda"
        case "ARG": self.init(rawValue:"🇦🇷") // "Argentina"
        case "ARM": self.init(rawValue:"🇦🇲") // "Armenia"
        case "ABW": self.init(rawValue:"🇦🇼") // "Aruba"
        case "AUS": self.init(rawValue:"🇦🇺") // "Australia"
        case "AUT": self.init(rawValue:"🇦🇹") // "Austria"
        case "AZE": self.init(rawValue:"🇦🇿") // "Azerbaijan"
        case "BHS": self.init(rawValue:"🇧🇸") // "Bahamas (the)"
        case "BHR": self.init(rawValue:"🇧🇭") // "Bahrain"
        case "BGD": self.init(rawValue:"🇧🇩") // "Bangladesh"
        case "BRB": self.init(rawValue:"🇧🇧") // "Barbados"
        case "BLR": self.init(rawValue:"🇧🇾") // "Belarus"
        case "BEL": self.init(rawValue:"🇧🇪") // "Belgium"
        case "BLZ": self.init(rawValue:"🇧🇿") // "Belize"
        case "BEN": self.init(rawValue:"🇧🇯") // "Benin"
        case "BMU": self.init(rawValue:"🇧🇲") // "Bermuda"
        case "BTN": self.init(rawValue:"🇧🇹") // "Bhutan"
        case "BOL": self.init(rawValue:"🇧🇴") // "Bolivia (Plurinational State of)"
        case "BES": self.init(rawValue:"🇧🇦") // "Bonaire, Sint Eustatius and Saba"
        case "BWA": self.init(rawValue:"🇧🇼") // "Botswana"
        case "BRA": self.init(rawValue:"🇧🇷") // "Brazil"
        case "IOT": self.init(rawValue:"🇮🇴") // "British Indian Ocean Territory (the)"
        case "BRN": self.init(rawValue:"🇧🇳") // "Brunei Darussalam"
        case "BGR": self.init(rawValue:"🇧🇬") // "Bulgaria"
        case "BFA": self.init(rawValue:"🇧🇫") // "Burkina Faso"
        case "BDI": self.init(rawValue:"🇧🇮") // "Burundi"
        case "CPV": self.init(rawValue:"🇨🇻") // "Cabo Verde"
        case "KHM": self.init(rawValue:"🇰🇭") // "Cambodia"
        case "CMR": self.init(rawValue:"🇨🇲") // "Cameroon"
        case "CAN": self.init(rawValue:"🇨🇦") // "Canada"
        case "CYM": self.init(rawValue:"🇰🇾") // "Cayman Islands (the)"
        case "CAF": self.init(rawValue:"🇨🇫") // "Central African Republic (the)"
        case "TCD": self.init(rawValue:"🇹🇩") // "Chad"
        case "CHL": self.init(rawValue:"🇨🇱") // "Chile"
        case "CHN": self.init(rawValue:"🇨🇳") // "China"
        case "CXR": self.init(rawValue:"🇨🇽") // "Christmas Island"
        case "CCK": self.init(rawValue:"🇨🇨") // "Cocos (Keeling) Islands (the)"
        case "COL": self.init(rawValue:"🇨🇴") // "Colombia"
        case "COM": self.init(rawValue:"🇰🇲") // "Comoros (the)"
        case "COD": self.init(rawValue:"🇨🇩") // "Congo (the Democratic Republic of the)"
        case "COG": self.init(rawValue:"🇨🇬") // "Congo (the)"
        case "COK": self.init(rawValue:"🇨🇰") // "Cook Islands (the)"
        case "CRI": self.init(rawValue:"🇨🇷") // "Costa Rica"
        case "HRV": self.init(rawValue:"🇭🇷") // "Croatia"
        case "CUB": self.init(rawValue:"🇨🇺") // "Cuba"
        case "CUW": self.init(rawValue:"🇨🇼") // "Curaçao"
        case "CYP": self.init(rawValue:"🇨🇾") // "Cyprus"
        case "CZE": self.init(rawValue:"🇨🇿") // "Czechia"
        case "CIV": self.init(rawValue:"🇨🇮") // "Côte d'Ivoire"
        case "DNK": self.init(rawValue:"🇩🇰") // "Denmark"
        case "DJI": self.init(rawValue:"🇩🇯") // "Djibouti"
        case "DMA": self.init(rawValue:"🇩🇲") // "Dominica"
        case "DOM": self.init(rawValue:"🇩🇴") // "Dominican Republic (the)"
        case "ECU": self.init(rawValue:"🇪🇨") // "Ecuador"
        case "EGY": self.init(rawValue:"🇪🇬") // "Egypt"
        case "SLV": self.init(rawValue:"🇸🇻") // "El Salvador"
        case "GNQ": self.init(rawValue:"🇬🇶") // "Equatorial Guinea"
        case "ERI": self.init(rawValue:"🇪🇷") // "Eritrea"
        case "EST": self.init(rawValue:"🇪🇪") // "Estonia"
        case "SWZ": self.init(rawValue:"🇸🇿") // "Eswatini"
        case "ETH": self.init(rawValue:"🇪🇹") // "Ethiopia"
        case "FLK": self.init(rawValue:"🇫🇰") // "Falkland Islands (the) [Malvinas]"
        case "FRO": self.init(rawValue:"🇫🇴") // "Faroe Islands (the)"
        case "FJI": self.init(rawValue:"🇫🇯") // "Fiji"
        case "FIN": self.init(rawValue:"🇫🇮") // "Finland"
        case "FRA": self.init(rawValue:"🇫🇷") // "France"
        case "GUF": self.init(rawValue:"🇬🇫") // "French Guiana"
        case "PYF": self.init(rawValue:"🇵🇫") // "French Polynesia"
        case "ATF": self.init(rawValue:"🇹🇫") // "French Southern Territories (the)"
        case "GAB": self.init(rawValue:"🇬🇦") // "Gabon"
        case "GMB": self.init(rawValue:"🇬🇲") // "Gambia (the)"
        case "GEO": self.init(rawValue:"🇬🇪") // "Georgia"
        case "DEU": self.init(rawValue:"🇩🇪") // "Germany"
        case "GHA": self.init(rawValue:"🇬🇭") // "Ghana"
        case "GIB": self.init(rawValue:"🇬🇮") // "Gibraltar"
        case "GRC": self.init(rawValue:"🇬🇷") // "Greece"
        case "GRL": self.init(rawValue:"🇬🇱") // "Greenland"
        case "GRD": self.init(rawValue:"🇬🇩") // "Grenada"
        case "GLP": self.init(rawValue:"🇬🇵") // "Guadeloupe"
        case "GUM": self.init(rawValue:"🇬🇺") // "Guam"
        case "GTM": self.init(rawValue:"🇬🇹") // "Guatemala"
        case "GGY": self.init(rawValue:"🇬🇬") // "Guernsey"
        case "GIN": self.init(rawValue:"🇬🇳") // "Guinea"
        case "GNB": self.init(rawValue:"🇬🇼") // "Guinea-Bissau"
        case "GUY": self.init(rawValue:"🇬🇾") // "Guyana"
        case "HTI": self.init(rawValue:"🇭🇹") // "Haiti"
        case "VAT": self.init(rawValue:"🇻🇦") // "Holy See (the)"
        case "HND": self.init(rawValue:"🇭🇳") // "Honduras"
        case "HKG": self.init(rawValue:"🇭🇰") // "Hong Kong"
        case "HUN": self.init(rawValue:"🇭🇺") // "Hungary"
        case "ISL": self.init(rawValue:"🇮🇸") // "Iceland"
        case "IND": self.init(rawValue:"🇮🇳") // "India"
        case "IDN": self.init(rawValue:"🇮🇩") // "Indonesia"
        case "IRN": self.init(rawValue:"🇮🇷") // "Iran (Islamic Republic of)"
        case "IRQ": self.init(rawValue:"🇮🇶") // "Iraq"
        case "IRL": self.init(rawValue:"🇮🇪") // "Ireland"
        case "IMN": self.init(rawValue:"🇮🇲") // "Isle of Man"
        case "ISR": self.init(rawValue:"🇮🇱") // "Israel"
        case "ITA": self.init(rawValue:"🇮🇹") // "Italy"
        case "JAM": self.init(rawValue:"🇯🇲") // "Jamaica"
        case "JPN": self.init(rawValue:"🇯🇵") // "Japan"
        case "JEY": self.init(rawValue:"🇯🇪") // "Jersey"
        case "JOR": self.init(rawValue:"🇯🇴") // "Jordan"
        case "KAZ": self.init(rawValue:"🇰🇿") // "Kazakhstan"
        case "KEN": self.init(rawValue:"🇰🇪") // "Kenya"
        case "KIR": self.init(rawValue:"🇰🇮") // "Kiribati"
        case "PRK": self.init(rawValue:"🇰🇵") // "Korea (the Democratic People's Republic of)"
        case "KOR": self.init(rawValue:"🇰🇷") // "Korea (the Republic of)"
        case "KWT": self.init(rawValue:"🇰🇼") // "Kuwait"
        case "KGZ": self.init(rawValue:"🇰🇬") // "Kyrgyzstan"
        case "LAO": self.init(rawValue:"🇱🇦") // "Lao People's Democratic Republic (the)"
        case "LVA": self.init(rawValue:"🇱🇻") // "Latvia"
        case "LBN": self.init(rawValue:"🇱🇧") // "Lebanon"
        case "LSO": self.init(rawValue:"🇱🇸") // "Lesotho"
        case "LBR": self.init(rawValue:"🇱🇷") // "Liberia"
        case "LBY": self.init(rawValue:"🇱🇾") // "Libya"
        case "LIE": self.init(rawValue:"🇱🇮") // "Liechtenstein"
        case "LTU": self.init(rawValue:"🇱🇹") // "Lithuania"
        case "LUX": self.init(rawValue:"🇱🇺") // "Luxembourg"
        case "MAC": self.init(rawValue:"🇲🇴") // "Macao"
        case "MDG": self.init(rawValue:"🇲🇬") // "Madagascar"
        case "MWI": self.init(rawValue:"🇲🇼") // "Malawi"
        case "MYS": self.init(rawValue:"🇲🇾") // "Malaysia"
        case "MDV": self.init(rawValue:"🇲🇻") // "Maldives"
        case "MLI": self.init(rawValue:"🇲🇱") // "Mali"
        case "MLT": self.init(rawValue:"🇲🇹") // "Malta"
        case "MHL": self.init(rawValue:"🇲🇭") // "Marshall Islands (the)"
        case "MTQ": self.init(rawValue:"🇲🇶") // "Martinique"
        case "MRT": self.init(rawValue:"🇲🇷") // "Mauritania"
        case "MUS": self.init(rawValue:"🇲🇺") // "Mauritius"
        case "MYT": self.init(rawValue:"🇾🇹") // "Mayotte"
        case "MEX": self.init(rawValue:"🇲🇽") // "Mexico"
        case "FSM": self.init(rawValue:"🇫🇲") // "Micronesia (Federated States of)"
        case "MDA": self.init(rawValue:"🇲🇩") // "Moldova (the Republic of)"
        case "MCO": self.init(rawValue:"🇲🇨") // "Monaco"
        case "MNG": self.init(rawValue:"🇲🇳") // "Mongolia"
        case "MNE": self.init(rawValue:"🇲🇪") // "Montenegro"
        case "MSR": self.init(rawValue:"🇲🇸") // "Montserrat"
        case "MAR": self.init(rawValue:"🇲🇦") // "Morocco"
        case "MOZ": self.init(rawValue:"🇲🇿") // "Mozambique"
        case "MMR": self.init(rawValue:"🇲🇲") // "Myanmar"
        case "NAM": self.init(rawValue:"🇳🇦") // "Namibia"
        case "NRU": self.init(rawValue:"🇳🇷") // "Nauru"
        case "NPL": self.init(rawValue:"🇳🇵") // "Nepal"
        case "NLD": self.init(rawValue:"🇳🇱") // "Netherlands (the)"
        case "NCL": self.init(rawValue:"🇳🇨") // "New Caledonia"
        case "NZL": self.init(rawValue:"🇳🇿") // "New Zealand"
        case "NIC": self.init(rawValue:"🇳🇮") // "Nicaragua"
        case "NER": self.init(rawValue:"🇳🇪") // "Niger (the)"
        case "NGA": self.init(rawValue:"🇳🇬") // "Nigeria"
        case "NIU": self.init(rawValue:"🇳🇺") // "Niue"
        case "NFK": self.init(rawValue:"🇳🇫") // "Norfolk Island"
        case "MNP": self.init(rawValue:"🇲🇵") // "Northern Mariana Islands (the)"
        case "NOR": self.init(rawValue:"🇳🇴") // "Norway"
        case "OMN": self.init(rawValue:"🇴🇲") // "Oman"
        case "PAK": self.init(rawValue:"🇵🇰") // "Pakistan"
        case "PLW": self.init(rawValue:"🇵🇼") // "Palau"
        case "PSE": self.init(rawValue:"🇵🇸") // "Palestine, State of"
        case "PAN": self.init(rawValue:"🇵🇦") // "Panama"
        case "PNG": self.init(rawValue:"🇵🇬") // "Papua New Guinea"
        case "PRY": self.init(rawValue:"🇵🇾") // "Paraguay"
        case "PER": self.init(rawValue:"🇵🇪") // "Peru"
        case "PHL": self.init(rawValue:"🇵🇭") // "Philippines (the)"
        case "PCN": self.init(rawValue:"🇵🇳") // "Pitcairn"
        case "POL": self.init(rawValue:"🇵🇱") // "Poland"
        case "PRT": self.init(rawValue:"🇵🇹") // "Portugal"
        case "PRI": self.init(rawValue:"🇵🇷") // "Puerto Rico"
        case "QAT": self.init(rawValue:"🇶🇦") // "Qatar"
        case "MKD": self.init(rawValue:"🇲🇰") // "Republic of North Macedonia"
        case "ROU": self.init(rawValue:"🇷🇴") // "Romania"
        case "RUS": self.init(rawValue:"🇷🇺") // "Russian Federation (the)"
        case "RWA": self.init(rawValue:"🇷🇼") // "Rwanda"
        case "REU": self.init(rawValue:"🇷🇪") // "Réunion"
        case "BLM": self.init(rawValue:"🇧🇱") // "Saint Barthélemy"
        case "SHN": self.init(rawValue:"🇬🇸") // "Saint Helena, Ascension and Tristan da Cunha"
        case "KNA": self.init(rawValue:"🇰🇳") // "Saint Kitts and Nevis"
        case "LCA": self.init(rawValue:"🇱🇨") // "Saint Lucia"
        case "SPM": self.init(rawValue:"🇵🇲") // "Saint Pierre and Miquelon"
        case "VCT": self.init(rawValue:"🇻🇨") // "Saint Vincent and the Grenadines"
        case "WSM": self.init(rawValue:"🇼🇸") // "Samoa"
        case "SMR": self.init(rawValue:"🇸🇲") // "San Marino"
        case "SAU": self.init(rawValue:"🇸🇦") // "Saudi Arabia"
        case "SEN": self.init(rawValue:"🇸🇳") // "Senegal"
        case "SRB": self.init(rawValue:"🇷🇸") // "Serbia"
        case "SYC": self.init(rawValue:"🇸🇨") // "Seychelles"
        case "SLE": self.init(rawValue:"🇸🇱") // "Sierra Leone"
        case "SGP": self.init(rawValue:"🇸🇬") // "Singapore"
        case "SXM": self.init(rawValue:"🇸🇽") // "Sint Maarten (Dutch part)"
        case "SVK": self.init(rawValue:"🇸🇰") // "Slovakia"
        case "SVN": self.init(rawValue:"🇸🇮") // "Slovenia"
        case "SLB": self.init(rawValue:"🇸🇧") // "Solomon Islands"
        case "SOM": self.init(rawValue:"🇸🇴") // "Somalia"
        case "ZAF": self.init(rawValue:"🇿🇦") // "South Africa"
        case "SGS": self.init(rawValue:"🇸🇭") // "South Georgia and the South Sandwich Islands"
        case "SSD": self.init(rawValue:"🇸🇸") // "South Sudan"
        case "ESP": self.init(rawValue:"🇪🇸") // "Spain"
        case "LKA": self.init(rawValue:"🇱🇰") // "Sri Lanka"
        case "SDN": self.init(rawValue:"🇸🇩") // "Sudan (the)"
        case "SUR": self.init(rawValue:"🇸🇷") // "Suriname"
        case "SWE": self.init(rawValue:"🇸🇪") // "Sweden"
        case "CHE": self.init(rawValue:"🇨🇭") // "Switzerland"
        case "SYR": self.init(rawValue:"🇸🇾") // "Syrian Arab Republic"
        case "TWN": self.init(rawValue:"🇹🇼") // "Taiwan (Province of China)"
        case "TJK": self.init(rawValue:"🇹🇯") // "Tajikistan"
        case "TZA": self.init(rawValue:"🇹🇿") // "Tanzania, United Republic of"
        case "THA": self.init(rawValue:"🇹🇭") // "Thailand"
        case "TLS": self.init(rawValue:"🇹🇱") // "Timor-Leste"
        case "TGO": self.init(rawValue:"🇹🇬") // "Togo"
        case "TKL": self.init(rawValue:"🇹🇰") // "Tokelau"
        case "TON": self.init(rawValue:"🇹🇴") // "Tonga"
        case "TTO": self.init(rawValue:"🇹🇹") // "Trinidad and Tobago"
        case "TUN": self.init(rawValue:"🇹🇳") // "Tunisia"
        case "TUR": self.init(rawValue:"🇹🇷") // "Turkey"
        case "TKM": self.init(rawValue:"🇹🇲") // "Turkmenistan"
        case "TCA": self.init(rawValue:"🇹🇨") // "Turks and Caicos Islands (the)"
        case "TUV": self.init(rawValue:"🇹🇻") // "Tuvalu"
        case "UGA": self.init(rawValue:"🇺🇬") // "Uganda"
        case "UKR": self.init(rawValue:"🇺🇦") // "Ukraine"
        case "ARE": self.init(rawValue:"🇦🇪") // "United Arab Emirates (the)"
        case "GBR": self.init(rawValue:"🇬🇧") // "United Kingdom of Great Britain and Northern Ireland"
        case "USA": self.init(rawValue:"🇺🇸") // "United States of America (the)"
        case "URY": self.init(rawValue:"🇺🇾") // "Uruguay"
        case "UZB": self.init(rawValue:"🇺🇿") // "Uzbekistan"
        case "VUT": self.init(rawValue:"🇻🇺") // "Vanuatu"
        case "VEN": self.init(rawValue:"🇻🇪") // "Venezuela (Bolivarian Republic of)"
        case "VNM": self.init(rawValue:"🇻🇳") // "Viet Nam"
        case "VGB": self.init(rawValue:"🇻🇬") // "Virgin Islands (British)"
        case "VIR": self.init(rawValue:"🇻🇮") // "Virgin Islands (U.S.)"
        case "WLF": self.init(rawValue:"🇼🇫") // "Wallis and Futuna"
        case "ESH": self.init(rawValue:"🇪🇭") // "Western Sahara"
        case "YEM": self.init(rawValue:"🇾🇪") // "Yemen"
        case "ZMB": self.init(rawValue:"🇿🇲") // "Zambia"
        case "ZWE": self.init(rawValue:"🇿🇼") // "Zimbabwe"
        case "ALA": self.init(rawValue:"🇦🇽") // "Åland Islands"
        default: self.init(rawValue:"🏳️‍🌈")
        }
    }

    public func name() -> String {
        switch self {
        case .RNB: return "Pride"
        case .AFG: return "Afghanistan"
        case .ALB: return "Albania"
        case .DZA: return "Algeria"
        case .ASM: return "American Samoa"
        case .AND: return "Andorra"
        case .AGO: return "Angola"
        case .AIA: return "Anguilla"
        case .ATA: return "Antarctica"
        case .ATG: return "Antigua and Barbuda"
        case .ARG: return "Argentina"
        case .ARM: return "Armenia"
        case .ABW: return "Aruba"
        case .AUS: return "Australia"
        case .AUT: return "Austria"
        case .AZE: return "Azerbaijan"
        case .BHS: return "Bahamas (the)"
        case .BHR: return "Bahrain"
        case .BGD: return "Bangladesh"
        case .BRB: return "Barbados"
        case .BLR: return "Belarus"
        case .BEL: return "Belgium"
        case .BLZ: return "Belize"
        case .BEN: return "Benin"
        case .BMU: return "Bermuda"
        case .BTN: return "Bhutan"
        case .BOL: return "Bolivia (Plurinational State of)"
        case .BES: return "Bonaire, Sint Eustatius and Saba"
        case .BWA: return "Botswana"
        case .BRA: return "Brazil"
        case .IOT: return "British Indian Ocean Territory (the)"
        case .BRN: return "Brunei Darussalam"
        case .BGR: return "Bulgaria"
        case .BFA: return "Burkina Faso"
        case .BDI: return "Burundi"
        case .CPV: return "Cabo Verde"
        case .KHM: return "Cambodia"
        case .CMR: return "Cameroon"
        case .CAN: return "Canada"
        case .CYM: return "Cayman Islands (the)"
        case .CAF: return "Central African Republic (the)"
        case .TCD: return "Chad"
        case .CHL: return "Chile"
        case .CHN: return "China"
        case .CXR: return "Christmas Island"
        case .CCK: return "Cocos (Keeling) Islands (the)"
        case .COL: return "Colombia"
        case .COM: return "Comoros (the)"
        case .COD: return "Congo (the Democratic Republic of the)"
        case .COG: return "Congo (the)"
        case .COK: return "Cook Islands (the)"
        case .CRI: return "Costa Rica"
        case .HRV: return "Croatia"
        case .CUB: return "Cuba"
        case .CUW: return "Curaçao"
        case .CYP: return "Cyprus"
        case .CZE: return "Czechia"
        case .CIV: return "Côte d'Ivoire"
        case .DNK: return "Denmark"
        case .DJI: return "Djibouti"
        case .DMA: return "Dominica"
        case .DOM: return "Dominican Republic (the)"
        case .ECU: return "Ecuador"
        case .EGY: return "Egypt"
        case .SLV: return "El Salvador"
        case .GNQ: return "Equatorial Guinea"
        case .ERI: return "Eritrea"
        case .EST: return "Estonia"
        case .SWZ: return "Eswatini"
        case .ETH: return "Ethiopia"
        case .FLK: return "Falkland Islands (the) [Malvinas]"
        case .FRO: return "Faroe Islands (the)"
        case .FJI: return "Fiji"
        case .FIN: return "Finland"
        case .FRA: return "France"
        case .GUF: return "French Guiana"
        case .PYF: return "French Polynesia"
        case .ATF: return "French Southern Territories (the)"
        case .GAB: return "Gabon"
        case .GMB: return "Gambia (the)"
        case .GEO: return "Georgia"
        case .DEU: return "Germany"
        case .GHA: return "Ghana"
        case .GIB: return "Gibraltar"
        case .GRC: return "Greece"
        case .GRL: return "Greenland"
        case .GRD: return "Grenada"
        case .GLP: return "Guadeloupe"
        case .GUM: return "Guam"
        case .GTM: return "Guatemala"
        case .GGY: return "Guernsey"
        case .GIN: return "Guinea"
        case .GNB: return "Guinea-Bissau"
        case .GUY: return "Guyana"
        case .HTI: return "Haiti"
        case .VAT: return "Holy See (the)"
        case .HND: return "Honduras"
        case .HKG: return "Hong Kong"
        case .HUN: return "Hungary"
        case .ISL: return "Iceland"
        case .IND: return "India"
        case .IDN: return "Indonesia"
        case .IRN: return "Iran (Islamic Republic of)"
        case .IRQ: return "Iraq"
        case .IRL: return "Ireland"
        case .IMN: return "Isle of Man"
        case .ISR: return "Israel"
        case .ITA: return "Italy"
        case .JAM: return "Jamaica"
        case .JPN: return "Japan"
        case .JEY: return "Jersey"
        case .JOR: return "Jordan"
        case .KAZ: return "Kazakhstan"
        case .KEN: return "Kenya"
        case .KIR: return "Kiribati"
        case .PRK: return "Korea (the Democratic People's Republic of)"
        case .KOR: return "Korea (the Republic of)"
        case .KWT: return "Kuwait"
        case .KGZ: return "Kyrgyzstan"
        case .LAO: return "Lao People's Democratic Republic (the)"
        case .LVA: return "Latvia"
        case .LBN: return "Lebanon"
        case .LSO: return "Lesotho"
        case .LBR: return "Liberia"
        case .LBY: return "Libya"
        case .LIE: return "Liechtenstein"
        case .LTU: return "Lithuania"
        case .LUX: return "Luxembourg"
        case .MAC: return "Macao"
        case .MDG: return "Madagascar"
        case .MWI: return "Malawi"
        case .MYS: return "Malaysia"
        case .MDV: return "Maldives"
        case .MLI: return "Mali"
        case .MLT: return "Malta"
        case .MHL: return "Marshall Islands (the)"
        case .MTQ: return "Martinique"
        case .MRT: return "Mauritania"
        case .MUS: return "Mauritius"
        case .MYT: return "Mayotte"
        case .MEX: return "Mexico"
        case .FSM: return "Micronesia (Federated States of)"
        case .MDA: return "Moldova (the Republic of)"
        case .MCO: return "Monaco"
        case .MNG: return "Mongolia"
        case .MNE: return "Montenegro"
        case .MSR: return "Montserrat"
        case .MAR: return "Morocco"
        case .MOZ: return "Mozambique"
        case .MMR: return "Myanmar"
        case .NAM: return "Namibia"
        case .NRU: return "Nauru"
        case .NPL: return "Nepal"
        case .NLD: return "Netherlands (the)"
        case .NCL: return "New Caledonia"
        case .NZL: return "New Zealand"
        case .NIC: return "Nicaragua"
        case .NER: return "Niger (the)"
        case .NGA: return "Nigeria"
        case .NIU: return "Niue"
        case .NFK: return "Norfolk Island"
        case .MNP: return "Northern Mariana Islands (the)"
        case .NOR: return "Norway"
        case .OMN: return "Oman"
        case .PAK: return "Pakistan"
        case .PLW: return "Palau"
        case .PSE: return "Palestine, State of"
        case .PAN: return "Panama"
        case .PNG: return "Papua New Guinea"
        case .PRY: return "Paraguay"
        case .PER: return "Peru"
        case .PHL: return "Philippines (the)"
        case .PCN: return "Pitcairn"
        case .POL: return "Poland"
        case .PRT: return "Portugal"
        case .PRI: return "Puerto Rico"
        case .QAT: return "Qatar"
        case .MKD: return "Republic of North Macedonia"
        case .ROU: return "Romania"
        case .RUS: return "Russian Federation (the)"
        case .RWA: return "Rwanda"
        case .REU: return "Réunion"
        case .BLM: return "Saint Barthélemy"
        case .SHN: return "Saint Helena, Ascension and Tristan da Cunha"
        case .KNA: return "Saint Kitts and Nevis"
        case .LCA: return "Saint Lucia"
        case .SPM: return "Saint Pierre and Miquelon"
        case .VCT: return "Saint Vincent and the Grenadines"
        case .WSM: return "Samoa"
        case .SMR: return "San Marino"
        case .SAU: return "Saudi Arabia"
        case .SEN: return "Senegal"
        case .SRB: return "Serbia"
        case .SYC: return "Seychelles"
        case .SLE: return "Sierra Leone"
        case .SGP: return "Singapore"
        case .SXM: return "Sint Maarten (Dutch part)"
        case .SVK: return "Slovakia"
        case .SVN: return "Slovenia"
        case .SLB: return "Solomon Islands"
        case .SOM: return "Somalia"
        case .ZAF: return "South Africa"
        case .SGS: return "South Georgia and the South Sandwich Islands"
        case .SSD: return "South Sudan"
        case .ESP: return "Spain"
        case .LKA: return "Sri Lanka"
        case .SDN: return "Sudan (the)"
        case .SUR: return "Suriname"
        case .SWE: return "Sweden"
        case .CHE: return "Switzerland"
        case .SYR: return "Syrian Arab Republic"
        case .TWN: return "Taiwan (Province of China)"
        case .TJK: return "Tajikistan"
        case .TZA: return "Tanzania, United Republic of"
        case .THA: return "Thailand"
        case .TLS: return "Timor-Leste"
        case .TGO: return "Togo"
        case .TKL: return "Tokelau"
        case .TON: return "Tonga"
        case .TTO: return "Trinidad and Tobago"
        case .TUN: return "Tunisia"
        case .TUR: return "Turkey"
        case .TKM: return "Turkmenistan"
        case .TCA: return "Turks and Caicos Islands (the)"
        case .TUV: return "Tuvalu"
        case .UGA: return "Uganda"
        case .UKR: return "Ukraine"
        case .ARE: return "United Arab Emirates (the)"
        case .GBR: return "United Kingdom of Great Britain and Northern Ireland"
        case .USA: return "United States of America (the)"
        case .URY: return "Uruguay"
        case .UZB: return "Uzbekistan"
        case .VUT: return "Vanuatu"
        case .VEN: return "Venezuela (Bolivarian Republic of)"
        case .VNM: return "Viet Nam"
        case .VGB: return "Virgin Islands (British)"
        case .VIR: return "Virgin Islands (U.S.)"
        case .WLF: return "Wallis and Futuna"
        case .ESH: return "Western Sahara"
        case .YEM: return "Yemen"
        case .ZMB: return "Zambia"
        case .ZWE: return "Zimbabwe"
        case .ALA: return "Åland Islands"
        }
    }
    
    public func region() -> Region {
        switch self {
        case .RNB: return .all
        case .AFG: return .asia
        case .ALB: return .europe                   //"Albania"
        case .DZA: return .africa                   //"Algeria"
        case .ASM: return .oceania                  //"American Samoa"
        case .AND: return .europe                   //"Andorra"
        case .AGO: return .africa                   //"Angola"
        case .AIA: return .northAmerica             //"Anguilla"
        case .ATA: return .antartica                //"Antarctica"
        case .ATG: return .northAmerica             //"Antigua and Barbuda"
        case .ARG: return .southAmerica             //"Argentina"
        case .ARM: return .europe                   //"Armenia"
        case .ABW: return .northAmerica             //"Aruba"
        case .AUS: return .australia                //"Australia"
        case .AUT: return .europe                   //"Austria"
        case .AZE: return .asia                     //"Azerbaijan"
        case .BHS: return .northAmerica             //"Bahamas (the)"
        case .BHR: return .asia                     //"Bahrain"
        case .BGD: return .asia                     //"Bangladesh"
        case .BRB: return .northAmerica             //"Barbados"
        case .BLR: return .europe                   //"Belarus"
        case .BEL: return .europe                   //"Belgium"
        case .BLZ: return .northAmerica             //"Belize"
        case .BEN: return .africa                   //"Benin"
        case .BMU: return .northAmerica             //"Bermuda"
        case .BTN: return .asia                     //"Bhutan"
        case .BOL: return .southAmerica             //"Bolivia (Plurinational State of)"
        case .BES: return .northAmerica             //"Bonaire, Sint Eustatius and Saba"
        case .BWA: return .africa                   //"Botswana"
        case .BRA: return .southAmerica             //"Brazil"
        case .IOT: return .asia                     //"British Indian Ocean Territory (the)"
        case .BRN: return .asia                     //"Brunei Darussalam"
        case .BGR: return .europe                   //"Bulgaria"
        case .BFA: return .africa                   //"Burkina Faso"
        case .BDI: return .africa                   //"Burundi"
        case .CPV: return .africa                   //"Cabo Verde"
        case .KHM: return .asia                     //"Cambodia"
        case .CMR: return .africa                   //"Cameroon"
        case .CAN: return .northAmerica             //"Canada"
        case .CYM: return .northAmerica             //"Cayman Islands (the)"
        case .CAF: return .africa                   //"Central African Republic (the)"
        case .TCD: return .africa                   //"Chad"
        case .CHL: return .southAmerica             //"Chile"
        case .CHN: return .asia                     //"China"
        case .CXR: return .asia                     //"Christmas Island"
        case .CCK: return .asia                     //"Cocos (Keeling) Islands (the)"
        case .COL: return .southAmerica             //"Colombia"
        case .COM: return .africa                   //"Comoros (the)"
        case .COD: return .africa                   //"Congo (the Democratic Republic of the)"
        case .COG: return .africa                   //"Congo (the)"
        case .COK: return .oceania                  //"Cook Islands (the)"
        case .CRI: return .southAmerica             //"Costa Rica"
        case .HRV: return .europe                   //"Croatia"
        case .CUB: return .southAmerica             //"Cuba"
        case .CUW: return .northAmerica             //"Curaçao"
        case .CYP: return .europe                   //"Cyprus"
        case .CZE: return .europe                   //"Czechia"
        case .CIV: return .africa                   //"Côte d'Ivoire"
        case .DNK: return .europe                   //"Denmark"
        case .DJI: return .africa                   //"Djibouti"
        case .DMA: return .northAmerica             //"Dominica"
        case .DOM: return .northAmerica             //"Dominican Republic (the)"
        case .ECU: return .southAmerica             //"Ecuador"
        case .EGY: return .africa                   //"Egypt"
        case .SLV: return .northAmerica             //"El Salvador"
        case .GNQ: return .africa                   //"Equatorial Guinea"
        case .ERI: return .africa                   //"Eritrea"
        case .EST: return .europe                   //"Estonia"
        case .SWZ: return .africa                   //"Eswatini"
        case .ETH: return .africa                   //"Ethiopia"
        case .FLK: return .southAmerica             //"Falkland Islands (the) [Malvinas]"
        case .FRO: return .europe                   //"Faroe Islands (the)"
        case .FJI: return .oceania                  //"Fiji"
        case .FIN: return .europe                   //"Finland"
        case .FRA: return .europe                   //"France"
        case .GUF: return .southAmerica             //"French Guiana"
        case .PYF: return .oceania                  //"French Polynesia"
        case .ATF: return .oceania                  //"French Southern Territories (the)"
        case .GAB: return .africa                   //"Gabon"
        case .GMB: return .africa                   //"Gambia (the)"
        case .GEO: return .europe                   //"Georgia"
        case .DEU: return .europe                   //"Germany"
        case .GHA: return .africa                   //"Ghana"
        case .GIB: return .europe                   //"Gibraltar"
        case .GRC: return .europe                   //"Greece"
        case .GRL: return .northAmerica             //"Greenland"
        case .GRD: return .northAmerica             //"Grenada"
        case .GLP: return .northAmerica             //"Guadeloupe"
        case .GUM: return .southAmerica             //"Guam"
        case .GTM: return .southAmerica             //"Guatemala"
        case .GGY: return .europe                   //"Guernsey"
        case .GIN: return .africa                   //"Guinea"
        case .GNB: return .africa                   //"Guinea-Bissau"
        case .GUY: return .southAmerica             //"Guyana"
        case .HTI: return .northAmerica             //"Haiti"
        case .VAT: return .europe                   //"Holy See (the)"
        case .HND: return .northAmerica             //"Honduras"
        case .HKG: return .asia                     //"Hong Kong"
        case .HUN: return .europe                   //"Hungary"
        case .ISL: return .europe                   //"Iceland"
        case .IND: return .asia                     //"India"
        case .IDN: return .asia                     //"Indonesia"
        case .IRN: return .asia                     //"Iran (Islamic Republic of)"
        case .IRQ: return .asia                     //"Iraq"
        case .IRL: return .europe                   //"Ireland"
        case .IMN: return .europe                   //"Isle of Man"
        case .ISR: return .europe                   //"Israel"
        case .ITA: return .europe                   //"Italy"
        case .JAM: return .northAmerica             //"Jamaica"
        case .JPN: return .asia                     //"Japan"
        case .JEY: return .europe                   //"Jersey"
        case .JOR: return .asia                     //"Jordan"
        case .KAZ: return .europe                   //"Kazakhstan"
        case .KEN: return .africa                   //"Kenya"
        case .KIR: return .oceania                  //"Kiribati"
        case .PRK: return .asia                     //"Korea (the Democratic People's Republic of)"
        case .KOR: return .asia                     //"Korea (the Republic of)"
        case .KWT: return .asia                     //"Kuwait"
        case .KGZ: return .asia                     //"Kyrgyzstan"
        case .LAO: return .asia                     //"Lao People's Democratic Republic (the)"
        case .LVA: return .europe                   //"Latvia"
        case .LBN: return .asia                     //"Lebanon"
        case .LSO: return .africa                   //"Lesotho"
        case .LBR: return .africa                   //"Liberia"
        case .LBY: return .africa                   //"Libya"
        case .LIE: return .europe                   //"Liechtenstein"
        case .LTU: return .europe                   //"Lithuania"
        case .LUX: return .europe                   //"Luxembourg"
        case .MAC: return .asia                     //"Macao"
        case .MDG: return .africa                   //"Madagascar"
        case .MWI: return .africa                   //"Malawi"
        case .MYS: return .asia                     //"Malaysia"
        case .MDV: return .asia                     //"Maldives"
        case .MLI: return .africa                   //"Mali"
        case .MLT: return .europe                   //"Malta"
        case .MHL: return .oceania                  //"Marshall Islands (the)"
        case .MTQ: return .northAmerica             //"Martinique"
        case .MRT: return .africa                   //"Mauritania"
        case .MUS: return .africa                   //"Mauritius"
        case .MYT: return .africa                   //"Mayotte"
        case .MEX: return .southAmerica             //"Mexico"
        case .FSM: return .oceania                  //"Micronesia (Federated States of)"
        case .MDA: return .europe                   //"Moldova (the Republic of)"
        case .MCO: return .europe                   //"Monaco"
        case .MNG: return .asia                     //"Mongolia"
        case .MNE: return .europe                   //"Montenegro"
        case .MSR: return .northAmerica             //"Montserrat"
        case .MAR: return .africa                   //"Morocco"
        case .MOZ: return .africa                   //"Mozambique"
        case .MMR: return .asia                     //"Myanmar"
        case .NAM: return .africa                   //"Namibia"
        case .NRU: return .oceania                  //"Nauru"
        case .NPL: return .asia                     //"Nepal"
        case .NLD: return .europe                   //"Netherlands (the)"
        case .NCL: return .oceania                  //"New Caledonia"
        case .NZL: return .oceania                  //"New Zealand"
        case .NIC: return .northAmerica             //"Nicaragua"
        case .NER: return .africa                   //"Niger (the)"
        case .NGA: return .africa                   //"Nigeria"
        case .NIU: return .oceania                  //"Niue"
        case .NFK: return .oceania                  //"Norfolk Island"
        case .MNP: return .oceania                  //"Northern Mariana Islands (the)"
        case .NOR: return .europe                   //"Norway"
        case .OMN: return .asia                     //"Oman"
        case .PAK: return .asia                     //"Pakistan"
        case .PLW: return .oceania                  //"Palau"
        case .PSE: return .asia                     //"Palestine, State of"
        case .PAN: return .northAmerica             //"Panama"
        case .PNG: return .africa                   //"Papua New Guinea"
        case .PRY: return .southAmerica             //"Paraguay"
        case .PER: return .southAmerica             //"Peru"
        case .PHL: return .asia                     //"Philippines (the)"
        case .PCN: return .oceania                  //"Pitcairn"
        case .POL: return .europe                   //"Poland"
        case .PRT: return .europe                   //"Portugal"
        case .PRI: return .northAmerica             //"Puerto Rico"
        case .QAT: return .asia                     //"Qatar"
        case .MKD: return .africa                   //"Republic of North Macedonia"
        case .ROU: return .europe                   //"Romania"
        case .RUS: return .asia                     //"Russian Federation (the)"
        case .RWA: return .africa                   //"Rwanda"
        case .REU: return .africa                   //"Réunion"
        case .BLM: return .northAmerica             //"Saint Barthélemy"
        case .SHN: return .africa                   //"Saint Helena, Ascension and Tristan da Cunha"
        case .KNA: return .northAmerica             //"Saint Kitts and Nevis"
        case .LCA: return .northAmerica             //"Saint Lucia"
        case .SPM: return .northAmerica             //"Saint Pierre and Miquelon"
        case .VCT: return .northAmerica             //"Saint Vincent and the Grenadines"
        case .WSM: return .oceania                  //"Samoa"
        case .SMR: return .europe                   //"San Marino"
        case .SAU: return .asia                     //"Saudi Arabia"
        case .SEN: return .africa                   //"Senegal"
        case .SRB: return .europe                   //"Serbia"
        case .SYC: return .africa                   //"Seychelles"
        case .SLE: return .africa                   //"Sierra Leone"
        case .SGP: return .asia                     //"Singapore"
        case .SXM: return .northAmerica             //"Sint Maarten (Dutch part)"
        case .SVK: return .europe                   //"Slovakia"
        case .SVN: return .europe                   //"Slovenia"
        case .SLB: return .oceania                  //"Solomon Islands"
        case .SOM: return .africa                   //"Somalia"
        case .ZAF: return .africa                   //"South Africa"
        case .SGS: return .antartica                //"South Georgia and the South Sandwich Islands"
        case .SSD: return .africa                   //"South Sudan"
        case .ESP: return .europe                   //"Spain"
        case .LKA: return .asia                     //"Sri Lanka"
        case .SDN: return .africa                   //"Sudan (the)"
        case .SUR: return .southAmerica             //"Suriname"
        case .SWE: return .europe                   //"Sweden"
        case .CHE: return .europe                   //"Switzerland"
        case .SYR: return .asia                     //"Syrian Arab Republic"
        case .TWN: return .asia                     //"Taiwan (Province of China)"
        case .TJK: return .asia                     //"Tajikistan"
        case .TZA: return .africa                   //"Tanzania, United Republic of"
        case .THA: return .asia                     //"Thailand"
        case .TLS: return .asia                     //"Timor-Leste"
        case .TGO: return .africa                   //"Togo"
        case .TKL: return .oceania                  //"Tokelau"
        case .TON: return .oceania                  //"Tonga"
        case .TTO: return .northAmerica             //"Trinidad and Tobago"
        case .TUN: return .africa                   //"Tunisia"
        case .TUR: return .europe                   //"Turkey"
        case .TKM: return .asia                     //"Turkmenistan"
        case .TCA: return .northAmerica             //"Turks and Caicos Islands (the)"
        case .TUV: return .oceania                  //"Tuvalu"
        case .UGA: return .africa                   //"Uganda"
        case .UKR: return .europe                   //"Ukraine"
        case .ARE: return .asia                     //"United Arab Emirates (the)"
        case .GBR: return .europe                   //"United Kingdom of Great Britain and Northern Ireland"
        case .USA: return .northAmerica             //"United States of America (the)"
        case .URY: return .southAmerica             //"Uruguay"
        case .UZB: return .asia                     //"Uzbekistan"
        case .VUT: return .oceania                  //"Vanuatu"
        case .VEN: return .southAmerica             //"Venezuela (Bolivarian Republic of)"
        case .VNM: return .asia                     //"Viet Nam"
        case .VGB: return .northAmerica             //"Virgin Islands (British)"
        case .VIR: return .northAmerica             //"Virgin Islands (U.S.)"
        case .WLF: return .oceania                  //"Wallis and Futuna"
        case .ESH: return .africa                   //"Western Sahara"
        case .YEM: return .asia                     //"Yemen"
        case .ZMB: return .africa                   //"Zambia"
        case .ZWE: return .africa                   //"Zimbabwe"
        case .ALA: return .europe                   //"Åland Islands"
        }
    }

    public func alpha3() -> String {
        switch self {
        case .RNB: return "RNB" //.all
        case .AFG: return "AFG" //.asia
        case .ALB: return "ALB" //.europe                   //"Albania"
        case .DZA: return "DZA" //.africa                   //"Algeria"
        case .ASM: return "ASM" //.oceania                  //"American Samoa"
        case .AND: return "AND" //.europe                   //"Andorra"
        case .AGO: return "AGO" //.africa                   //"Angola"
        case .AIA: return "AIA" //.northAmerica             //"Anguilla"
        case .ATA: return "ATA" //.antartica                //"Antarctica"
        case .ATG: return "ATG" //.northAmerica             //"Antigua and Barbuda"
        case .ARG: return "ARG" //.southAmerica             //"Argentina"
        case .ARM: return "ARM" //.europe                   //"Armenia"
        case .ABW: return "ABW" //.northAmerica             //"Aruba"
        case .AUS: return "AUS" //.australia                //"Australia"
        case .AUT: return "AUT" //.europe                   //"Austria"
        case .AZE: return "AZE" //.asia                     //"Azerbaijan"
        case .BHS: return "BHS" //.northAmerica             //"Bahamas (the)"
        case .BHR: return "BHR" //.asia                     //"Bahrain"
        case .BGD: return "BGD" //.asia                     //"Bangladesh"
        case .BRB: return "BRB" //.northAmerica             //"Barbados"
        case .BLR: return "BLR" //.europe                   //"Belarus"
        case .BEL: return "BEL" //.europe                   //"Belgium"
        case .BLZ: return "BLZ" //.northAmerica             //"Belize"
        case .BEN: return "BEN" //.africa                   //"Benin"
        case .BMU: return "BMU" //.northAmerica             //"Bermuda"
        case .BTN: return "BTN" //.asia                     //"Bhutan"
        case .BOL: return "BOL" //.southAmerica             //"Bolivia (Plurinational State of)"
        case .BES: return "BES" //.northAmerica             //"Bonaire, Sint Eustatius and Saba"
        case .BWA: return "BWA" //.africa                   //"Botswana"
        case .BRA: return "BRA" //.southAmerica             //"Brazil"
        case .IOT: return "IOT" //.asia                     //"British Indian Ocean Territory (the)"
        case .BRN: return "BRN" //.asia                     //"Brunei Darussalam"
        case .BGR: return "BGR" //.europe                   //"Bulgaria"
        case .BFA: return "BFA" //.africa                   //"Burkina Faso"
        case .BDI: return "BDI" //.africa                   //"Burundi"
        case .CPV: return "CPV" //.africa                   //"Cabo Verde"
        case .KHM: return "KHM" //.asia                     //"Cambodia"
        case .CMR: return "CMR" //.africa                   //"Cameroon"
        case .CAN: return "CAN" //.northAmerica             //"Canada"
        case .CYM: return "CYM" //.northAmerica             //"Cayman Islands (the)"
        case .CAF: return "CAF" //.africa                   //"Central African Republic (the)"
        case .TCD: return "TCD" //.africa                   //"Chad"
        case .CHL: return "CHL" //.southAmerica             //"Chile"
        case .CHN: return "CHN" //.asia                     //"China"
        case .CXR: return "CXR" //.asia                     //"Christmas Island"
        case .CCK: return "CCK" //.asia                     //"Cocos (Keeling) Islands (the)"
        case .COL: return "COL" //.southAmerica             //"Colombia"
        case .COM: return "COM" //.africa                   //"Comoros (the)"
        case .COD: return "COD" //.africa                   //"Congo (the Democratic Republic of the)"
        case .COG: return "COG" //.africa                   //"Congo (the)"
        case .COK: return "COK" //.oceania                  //"Cook Islands (the)"
        case .CRI: return "CRI" //.southAmerica             //"Costa Rica"
        case .HRV: return "HRV" //.europe                   //"Croatia"
        case .CUB: return "CUB" //.southAmerica             //"Cuba"
        case .CUW: return "CUW" //.northAmerica             //"Curaçao"
        case .CYP: return "CYP" //.europe                   //"Cyprus"
        case .CZE: return "CZE" //.europe                   //"Czechia"
        case .CIV: return "CIV" //.africa                   //"Côte d'Ivoire"
        case .DNK: return "DNK" //.europe                   //"Denmark"
        case .DJI: return "DJI" //.africa                   //"Djibouti"
        case .DMA: return "DMA" //.northAmerica             //"Dominica"
        case .DOM: return "DOM" //.northAmerica             //"Dominican Republic (the)"
        case .ECU: return "ECU" //.southAmerica             //"Ecuador"
        case .EGY: return "EGY" //.africa                   //"Egypt"
        case .SLV: return "SLV" //.northAmerica             //"El Salvador"
        case .GNQ: return "GNQ" //.africa                   //"Equatorial Guinea"
        case .ERI: return "ERI" //.africa                   //"Eritrea"
        case .EST: return "EST" //.europe                   //"Estonia"
        case .SWZ: return "SWZ" //.africa                   //"Eswatini"
        case .ETH: return "ETH" //.africa                   //"Ethiopia"
        case .FLK: return "FLK" //.southAmerica             //"Falkland Islands (the) [Malvinas]"
        case .FRO: return "FRO" //.europe                   //"Faroe Islands (the)"
        case .FJI: return "FJI" //.oceania                  //"Fiji"
        case .FIN: return "FIN" //.europe                   //"Finland"
        case .FRA: return "FRA" //.europe                   //"France"
        case .GUF: return "GUF" //.southAmerica             //"French Guiana"
        case .PYF: return "PYF" //.oceania                  //"French Polynesia"
        case .ATF: return "ATF" //.oceania                  //"French Southern Territories (the)"
        case .GAB: return "GAB" //.africa                   //"Gabon"
        case .GMB: return "GMB" //.africa                   //"Gambia (the)"
        case .GEO: return "GEO" //.europe                   //"Georgia"
        case .DEU: return "DEU" //.europe                   //"Germany"
        case .GHA: return "GHA" //.africa                   //"Ghana"
        case .GIB: return "GIB" //.europe                   //"Gibraltar"
        case .GRC: return "GRC" //.europe                   //"Greece"
        case .GRL: return "GRL" //.northAmerica             //"Greenland"
        case .GRD: return "GRD" //.northAmerica             //"Grenada"
        case .GLP: return "GLP" //.northAmerica             //"Guadeloupe"
        case .GUM: return "GUM" //.southAmerica             //"Guam"
        case .GTM: return "GTM" //.southAmerica             //"Guatemala"
        case .GGY: return "GGY" //.europe                   //"Guernsey"
        case .GIN: return "GIN" //.africa                   //"Guinea"
        case .GNB: return "GNB" //.africa                   //"Guinea-Bissau"
        case .GUY: return "GUY" //.southAmerica             //"Guyana"
        case .HTI: return "HTI" //.northAmerica             //"Haiti"
        case .VAT: return "VAT" //.europe                   //"Holy See (the)"
        case .HND: return "HND" //.northAmerica             //"Honduras"
        case .HKG: return "HKG" //.asia                     //"Hong Kong"
        case .HUN: return "HUN" //.europe                   //"Hungary"
        case .ISL: return "ISL" //.europe                   //"Iceland"
        case .IND: return "IND" //.asia                     //"India"
        case .IDN: return "IDN" //.asia                     //"Indonesia"
        case .IRN: return "IRN" //.asia                     //"Iran (Islamic Republic of)"
        case .IRQ: return "IRQ" //.asia                     //"Iraq"
        case .IRL: return "IRL" //.europe                   //"Ireland"
        case .IMN: return "IMN" //.europe                   //"Isle of Man"
        case .ISR: return "ISR" //.europe                   //"Israel"
        case .ITA: return "ITA" //.europe                   //"Italy"
        case .JAM: return "JAM" //.northAmerica             //"Jamaica"
        case .JPN: return "JPN" //.asia                     //"Japan"
        case .JEY: return "JEY" //.europe                   //"Jersey"
        case .JOR: return "JOR" //.asia                     //"Jordan"
        case .KAZ: return "KAZ" //.europe                   //"Kazakhstan"
        case .KEN: return "KEN" //.africa                   //"Kenya"
        case .KIR: return "KIR" //.oceania                  //"Kiribati"
        case .PRK: return "PRK" //.asia                     //"Korea (the Democratic People's Republic of)"
        case .KOR: return "KOR" //.asia                     //"Korea (the Republic of)"
        case .KWT: return "KWT" //.asia                     //"Kuwait"
        case .KGZ: return "KGZ" //.asia                     //"Kyrgyzstan"
        case .LAO: return "LAO" //.asia                     //"Lao People's Democratic Republic (the)"
        case .LVA: return "LVA" //.europe                   //"Latvia"
        case .LBN: return "LBN" //.asia                     //"Lebanon"
        case .LSO: return "LSO" //.africa                   //"Lesotho"
        case .LBR: return "LBR" //.africa                   //"Liberia"
        case .LBY: return "LBY" //.africa                   //"Libya"
        case .LIE: return "LIE" //.europe                   //"Liechtenstein"
        case .LTU: return "LTU" //.europe                   //"Lithuania"
        case .LUX: return "LUX" //.europe                   //"Luxembourg"
        case .MAC: return "MAC" //.asia                     //"Macao"
        case .MDG: return "MDG" //.africa                   //"Madagascar"
        case .MWI: return "MWI" //.africa                   //"Malawi"
        case .MYS: return "MYS" //.asia                     //"Malaysia"
        case .MDV: return "MDV" //.asia                     //"Maldives"
        case .MLI: return "MLI" //.africa                   //"Mali"
        case .MLT: return "MLT" //.europe                   //"Malta"
        case .MHL: return "MHL" //.oceania                  //"Marshall Islands (the)"
        case .MTQ: return "MTQ" //.northAmerica             //"Martinique"
        case .MRT: return "MRT" //.africa                   //"Mauritania"
        case .MUS: return "MUS" //.africa                   //"Mauritius"
        case .MYT: return "MYT" //.africa                   //"Mayotte"
        case .MEX: return "MEX" //.southAmerica             //"Mexico"
        case .FSM: return "FSM" //.oceania                  //"Micronesia (Federated States of)"
        case .MDA: return "MDA" //.europe                   //"Moldova (the Republic of)"
        case .MCO: return "MCO" //.europe                   //"Monaco"
        case .MNG: return "MNG" //.asia                     //"Mongolia"
        case .MNE: return "MNE" //.europe                   //"Montenegro"
        case .MSR: return "MSR" //.northAmerica             //"Montserrat"
        case .MAR: return "MAR" //.africa                   //"Morocco"
        case .MOZ: return "MOZ" //.africa                   //"Mozambique"
        case .MMR: return "MMR" //.asia                     //"Myanmar"
        case .NAM: return "NAM" //.africa                   //"Namibia"
        case .NRU: return "NRU" //.oceania                  //"Nauru"
        case .NPL: return "NPL" //.asia                     //"Nepal"
        case .NLD: return "NLD" //.europe                   //"Netherlands (the)"
        case .NCL: return "NCL" //.oceania                  //"New Caledonia"
        case .NZL: return "NZL" //.oceania                  //"New Zealand"
        case .NIC: return "NIC" //.northAmerica             //"Nicaragua"
        case .NER: return "NER" //.africa                   //"Niger (the)"
        case .NGA: return "NGA" //.africa                   //"Nigeria"
        case .NIU: return "NIU" //.oceania                  //"Niue"
        case .NFK: return "NFK" //.oceania                  //"Norfolk Island"
        case .MNP: return "MNP" //.oceania                  //"Northern Mariana Islands (the)"
        case .NOR: return "NOR" //.europe                   //"Norway"
        case .OMN: return "OMN" //.asia                     //"Oman"
        case .PAK: return "PAK" //.asia                     //"Pakistan"
        case .PLW: return "PLW" //.oceania                  //"Palau"
        case .PSE: return "PSE" //.asia                     //"Palestine, State of"
        case .PAN: return "PAN" //.northAmerica             //"Panama"
        case .PNG: return "PNG" //.africa                   //"Papua New Guinea"
        case .PRY: return "PRY" //.southAmerica             //"Paraguay"
        case .PER: return "PER" //.southAmerica             //"Peru"
        case .PHL: return "PHL" //.asia                     //"Philippines (the)"
        case .PCN: return "PCN" //.oceania                  //"Pitcairn"
        case .POL: return "POL" //.europe                   //"Poland"
        case .PRT: return "PRT" //.europe                   //"Portugal"
        case .PRI: return "PRI" //.northAmerica             //"Puerto Rico"
        case .QAT: return "QAT" //.asia                     //"Qatar"
        case .MKD: return "MKD" //.africa                   //"Republic of North Macedonia"
        case .ROU: return "ROU" //.europe                   //"Romania"
        case .RUS: return "RUS" //.asia                     //"Russian Federation (the)"
        case .RWA: return "RWA" //.africa                   //"Rwanda"
        case .REU: return "REU" //.africa                   //"Réunion"
        case .BLM: return "BLM" //.northAmerica             //"Saint Barthélemy"
        case .SHN: return "SHN" //.africa                   //"Saint Helena, Ascension and Tristan da Cunha"
        case .KNA: return "KNA" //.northAmerica             //"Saint Kitts and Nevis"
        case .LCA: return "LCA" //.northAmerica             //"Saint Lucia"
        case .SPM: return "SPM" //.northAmerica             //"Saint Pierre and Miquelon"
        case .VCT: return "VCT" //.northAmerica             //"Saint Vincent and the Grenadines"
        case .WSM: return "WSM" //.oceania                  //"Samoa"
        case .SMR: return "SMR" //.europe                   //"San Marino"
        case .SAU: return "SAU" //.asia                     //"Saudi Arabia"
        case .SEN: return "SEN" //.africa                   //"Senegal"
        case .SRB: return "SRB" //.europe                   //"Serbia"
        case .SYC: return "SYC" //.africa                   //"Seychelles"
        case .SLE: return "SLE" //.africa                   //"Sierra Leone"
        case .SGP: return "SGP" //.asia                     //"Singapore"
        case .SXM: return "SXM" //.northAmerica             //"Sint Maarten (Dutch part)"
        case .SVK: return "SVK" //.europe                   //"Slovakia"
        case .SVN: return "SVN" //.europe                   //"Slovenia"
        case .SLB: return "SLB" //.oceania                  //"Solomon Islands"
        case .SOM: return "SOM" //.africa                   //"Somalia"
        case .ZAF: return "ZAF" //.africa                   //"South Africa"
        case .SGS: return "SGS" //.antartica                //"South Georgia and the South Sandwich Islands"
        case .SSD: return "SSD" //.africa                   //"South Sudan"
        case .ESP: return "ESP" //.europe                   //"Spain"
        case .LKA: return "LKA" //.asia                     //"Sri Lanka"
        case .SDN: return "SDN" //.africa                   //"Sudan (the)"
        case .SUR: return "SUR" //.southAmerica             //"Suriname"
        case .SWE: return "SWE" //.europe                   //"Sweden"
        case .CHE: return "CHE" //.europe                   //"Switzerland"
        case .SYR: return "SYR" //.asia                     //"Syrian Arab Republic"
        case .TWN: return "TWN" //.asia                     //"Taiwan (Province of China)"
        case .TJK: return "TJK" //.asia                     //"Tajikistan"
        case .TZA: return "TZA" //.africa                   //"Tanzania, United Republic of"
        case .THA: return "THA" //.asia                     //"Thailand"
        case .TLS: return "TLS" //.asia                     //"Timor-Leste"
        case .TGO: return "TGO" //.africa                   //"Togo"
        case .TKL: return "TKL" //.oceania                  //"Tokelau"
        case .TON: return "TON" //.oceania                  //"Tonga"
        case .TTO: return "TTO" //.northAmerica             //"Trinidad and Tobago"
        case .TUN: return "TUN" //.africa                   //"Tunisia"
        case .TUR: return "TUR" //.europe                   //"Turkey"
        case .TKM: return "TKM" //.asia                     //"Turkmenistan"
        case .TCA: return "TCA" //.northAmerica             //"Turks and Caicos Islands (the)"
        case .TUV: return "TUV" //.oceania                  //"Tuvalu"
        case .UGA: return "UGA" //.africa                   //"Uganda"
        case .UKR: return "UKR" //.europe                   //"Ukraine"
        case .ARE: return "ARE" //.asia                     //"United Arab Emirates (the)"
        case .GBR: return "GBR" //.europe                   //"United Kingdom of Great Britain and Northern Ireland"
        case .USA: return "USA" //.northAmerica             //"United States of America (the)"
        case .URY: return "URY" //.southAmerica             //"Uruguay"
        case .UZB: return "UZB" //.asia                     //"Uzbekistan"
        case .VUT: return "VUT" //.oceania                  //"Vanuatu"
        case .VEN: return "VEN" //.southAmerica             //"Venezuela (Bolivarian Republic of)"
        case .VNM: return "VNM" //.asia                     //"Viet Nam"
        case .VGB: return "VGB" //.northAmerica             //"Virgin Islands (British)"
        case .VIR: return "VIR" //.northAmerica             //"Virgin Islands (U.S.)"
        case .WLF: return "WLF" //.oceania                  //"Wallis and Futuna"
        case .ESH: return "ESH" //.africa                   //"Western Sahara"
        case .YEM: return "YEM" //.asia                     //"Yemen"
        case .ZMB: return "ZMB" //.africa                   //"Zambia"
        case .ZWE: return "ZWE" //.africa                   //"Zimbabwe"
        case .ALA: return "ALA" //.europe                   //"Åland Islands"
        }
    }
}
